version: "3"

services:
  pong-db:
    image: mysql
    container_name: pong-db
    restart: always
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=W5QX1oxmj8k2u0b2xwUodot2tswLyhX683+OvvDzPhY=
      - MYSQL_DATABASE=DbPongFramework
    volumes:
      - ./data:/var/lib/mysql
      - ./config/db/my.cnf:/etc/mysql/my.cnf
      - ./config/db/conf.d:/etc/mysql/conf.d
    ports:
      - 3750:3306
    networks:
      - locale-network

  pong-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: pong-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    depends_on:
      - pong-web
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - locale-network

  pong-phpmyadmin:
    container_name: pong-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - ./phpmyadmin/phpmyadmin.conf:/etc/apache2/sites-available/phpmyadmin.conf:ro
      - ./phpmyadmin/phpmyadmin.conf:/etc/apache2/sites-enabled/phpmyadmin.conf:ro
    ports:
      - 80
    depends_on:
      - pong-db
    environment:
      - PMA_HOST=pong-db
      - MYSQL_USERNAME=admin7
      - MYSQL_ROOT_PASSWORD=me4Kk2o7VlfNyoLxU9YCQbB0JvXmQOz05hKJ8vUZOyc=
    networks:
      - locale-network

networks:
  locale-network:
    driver: bridge
